#!/bin/bash

BLOCKLY_RELEASE_BASE_URL="https://github.com/google/blockly/archive"
BLOCKLY_RELEASE_VERSION="1.20190215.0"

BLOCKLY_PKG_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

BLOCKLY_RELEASE_URL="${BLOCKLY_RELEASE_BASE_URL}/${BLOCKLY_RELEASE_VERSION}.tar.gz"

cd "${BLOCKLY_PKG_DIR}/data/public/" \
  && wget ${BLOCKLY_RELEASE_URL} \
  && tar -zxf "./${BLOCKLY_RELEASE_VERSION}.tar.gz" \
  && mv "blockly-${BLOCKLY_RELEASE_VERSION}" "blockly" \
  && rm -rf "./${BLOCKLY_RELEASE_VERSION}.tar.gz"
